# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache
#remote_theme: http[s]://github.com/nagymusic/nagymusic
repository: nagymusic/nagymusic.github.io

# Site Settings
locale                   : "en-US"
title                    : "nagyMusic"
title_separator          : "-"
name                     : &name "Zvony Nagy" # &name is a YAML anchor which can be *referenced later
description              : #&description "composer | scholar | performer"
#url                      : https://nagymusic.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#baseurl                  : "/nagymusic" # the subpath of your site, e.g. "/blog"
#repository               : "mmistakes/minimal-mistakes"
#teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman_v2", "staticman" "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : #6 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  #branch                 : "master"
  commitMessage          : # "New comment"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "_data/comments/{options.slug}"
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                : "6LdRBykTAAAAAFB46MnIu6ixuxwu9W1ihFF8G60Q"
  secret                 : "PznnZGu3P6eTHRPLORniSq+J61YEf+A9zmColXDM5icqF49gbunH51B8+h+i2IvewpuxtA9TFoK68TuhUp/X3YKmmqhXasegHYabY50fqF9nJh9npWNhvITdkQHeaOqnFXUIwxfiEeUt49Yoa2waRR7a5LdRAP3SVM8hz0KIBT4="

atom_feed:
  path                   : # blank (default) uses feed.xml

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia
algolia:
  application_id         : QB6HVGBSBA # YOUR_APPLICATION_ID
  index_name             : minimal_mistakes # YOUR_INDEX_NAME
  search_only_api_key    : 9d5014e5bbc77372547bce778dfa5663 # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (default), false
  files_to_exclude:
    - _posts/2017-11-28-post-exclude-search.md


# SEO Related
google_site_verification : "UA-3958729-1" # Replace this with your ID, or delete

# Reading Files
include:
  - .htaccess
  - _pages

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
